### PR TITLE
added theme changes for nweurope2016

### PR DESCRIPTION
**Pull request by jaapjansma**
Theme for CiviCon Northwest Europe 2016

### CODE REVIEW

**Comment by michaelmcandrew** [comment]
do you want me to pull this to production? Or can you do that?

On 20/04/16 09:57, Jaap Jansma wrote:
>
> Theme for CiviCon Northwest Europe 2016
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/civicrm/civicon/pull/28
>
>
>         Commit Summary
>
>   * added theme changes for nweurope2016
>
>
>         File Changes
>
>   * *A* sites/all/themes/nweurope2016/css/README.txt
>     <https://github.com/civicrm/civicon/pull/28/files#diff-0> (70)
>   * *A* sites/all/themes/nweurope2016/css/global.css
>     <https://github.com/civicrm/civicon/pull/28/files#diff-1> (446)
>   * *A* sites/all/themes/nweurope2016/css/images/.DS_Store
>     <https://github.com/civicrm/civicon/pull/28/files#diff-2> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/arrow-group-small.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-3> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/arrow-group.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-4> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/big-civis.gif
>     <https://github.com/civicrm/civicon/pull/28/files#diff-5> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/big-civis.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-6> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/bronze.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-7> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/clock.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-8> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/dude-60.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-9> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/dude-75.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-10> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/gold-normal.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-11> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/gold-wide.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-12> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/logo-postscript.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-13> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/logos-narrow.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-14> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/logos-normal.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-15> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/logos-wide.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-16> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/lunch-normal.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-17> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/lunch-wide.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-18> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/quote-bubble.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-19> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/silver-normal.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-20> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/silver-wide.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-21> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/slide-left.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-22> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/slide-right.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-23> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/speechbubble.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-24> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/tweety.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-25> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/tweety.xcf
>     <https://github.com/civicrm/civicon/pull/28/files#diff-26> (0)
>   * *A* sites/all/themes/nweurope2016/css/images/user.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-27> (0)
>   * *A*
>     sites/all/themes/nweurope2016/css/nweurope2016-alpha-default-narrow.css
>     <https://github.com/civicrm/civicon/pull/28/files#diff-28> (139)
>   * *A*
>     sites/all/themes/nweurope2016/css/nweurope2016-alpha-default-normal.css
>     <https://github.com/civicrm/civicon/pull/28/files#diff-29> (66)
>   * *A*
>     sites/all/themes/nweurope2016/css/nweurope2016-alpha-default-wide.css
>     <https://github.com/civicrm/civicon/pull/28/files#diff-30> (55)
>   * *A*
>     sites/all/themes/nweurope2016/css/nweurope2016-alpha-default.css
>     <https://github.com/civicrm/civicon/pull/28/files#diff-31> (1)
>   * *A* sites/all/themes/nweurope2016/logo.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-32> (0)
>   * *A* sites/all/themes/nweurope2016/nweurope2016.info
>     <https://github.com/civicrm/civicon/pull/28/files#diff-33> (354)
>   * *A* sites/all/themes/nweurope2016/preprocess/README.txt
>     <https://github.com/civicrm/civicon/pull/28/files#diff-34> (39)
>   * *A* sites/all/themes/nweurope2016/process/README.txt
>     <https://github.com/civicrm/civicon/pull/28/files#diff-35> (39)
>   * *A* sites/all/themes/nweurope2016/screenshot.png
>     <https://github.com/civicrm/civicon/pull/28/files#diff-36> (0)
>   * *A* sites/all/themes/nweurope2016/template.php
>     <https://github.com/civicrm/civicon/pull/28/files#diff-37> (12)
>   * *A* sites/all/themes/nweurope2016/templates/README.txt
>     <https://github.com/civicrm/civicon/pull/28/files#diff-38> (26)
>
>
>         Patch Links:
>
>   * https://github.com/civicrm/civicon/pull/28.patch
>   * https://github.com/civicrm/civicon/pull/28.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/civicrm/civicon/pull/28>
>

-- 
Michael McAndrew
https://civicrm.org
skype: michaelmcandrew
phone: +34 671 789 776

**Comment by jaapjansma** [comment]
I cannot pull this to production. So if you could do that?

**Comment by michaelmcandrew** [comment]
done - if you want to do more of this kind of thing in the future, we 
can look at getting you ssh access to the machine.

On 20/04/16 11:09, Jaap Jansma wrote:
>
> I cannot pull this to production. So if you could do that?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> <https://github.com/civicrm/civicon/pull/28#issuecomment-212364169>
>

-- 
Michael McAndrew
https://civicrm.org
skype: michaelmcandrew
phone: +34 671 789 776

**Comment by jaapjansma** [comment]
ssh access would be wonderfull.

**Comment by michaelmcandrew** [comment]
OK - have asked Yashi. See https://issues.civicrm.org/jira/browse/INFRA-180

Also, please see https://github.com/civicrm/civicon#to-deploy-changes

On 20/04/16 11:19, Jaap Jansma wrote:
>
> ssh access would be wonderfull.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> <https://github.com/civicrm/civicon/pull/28#issuecomment-212367343>
>

-- 
Michael McAndrew
https://civicrm.org
skype: michaelmcandrew
phone: +34 671 789 776

**Comment by jaapjansma** [comment]
Thanks @michaelmcandrew 
Could I also get write access to this repo?

**Comment by michaelmcandrew** [comment]
done

On 20/04/16 14:58, Jaap Jansma wrote:
>
> Thanks @michaelmcandrew <https://github.com/michaelmcandrew>
> Could I also get write access to this repo?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/civicrm/civicon/pull/28#issuecomment-212436432>
>

-- 
Michael McAndrew
https://civicrm.org
skype: michaelmcandrew
phone: +34 671 789 776

**Comment by jaapjansma** [comment]
Thanks!

**Pull request merged**
